<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm1.aspx.cs" Inherits="WebApplication4.WebForm1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:lp3ConnectionString2 %>" SelectCommand="SELECT * FROM [RegistroContable]" DeleteCommand="DELETE FROM RegistroContable WHERE (ID = ID)" UpdateCommand="UPDATE [RegistroContable] SET [IdCuenta] = @IdCuenta, [Monto] = @Monto, [Tipo] = @Tipo WHERE [ID] = ID" InsertCommand="INSERT INTO RegistroContable (IdCuenta, Monto, Tipo) values (IdCuenta, Monto, Tipo)">
               
                <UpdateParameters>
                    <asp:Parameter Name="IdCuenta" />
                    <asp:Parameter Name="Monto" />
                    <asp:Parameter Name="Tipo" />
                </UpdateParameters>
            </asp:SqlDataSource>
            <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:lp3ConnectionString2 %>" DeleteCommand="DELETE FROM Cuentas WHERE ID = ID" SelectCommand="SELECT ID as ID, descripcion FROM CUENTAS" UpdateCommand="UPDATE [Cuentas] SET [Descripcion] = @Descripcion WHERE ID = ID">
                <DeleteParameters>
                    <asp:Parameter Name="ID" />
                </DeleteParameters>
                <UpdateParameters>
                    <asp:Parameter Name="Descripcion" />
                    <asp:Parameter Name="ID" />
                </UpdateParameters>
            </asp:SqlDataSource>
            <asp:Label ID="Label1" runat="server" Text="IdCuenta"></asp:Label>
            <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
            <asp:Label ID="Label2" runat="server" Text="Monto"></asp:Label>
            <asp:TextBox ID="TextBox2" runat="server"></asp:TextBox>
            <asp:DropDownList ID="DropDownList1" runat="server" DataSourceID="SqlDataSource1" DataTextField="Tipo" DataValueField="Tipo"></asp:DropDownList>
            <asp:Button ID="Button1" runat="server" Text="Confirmar" OnClick="Button1_Click" />
            <asp:GridView ID="GridView1" runat="server" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" AllowSorting="True" AutoGenerateColumns="False" DataSourceID="SqlDataSource1" AllowPaging="True">
                <Columns>
                    <asp:BoundField DataField="ID" HeaderText="ID" InsertVisible="False" ReadOnly="True" SortExpression="ID" />
                    <asp:BoundField DataField="IdCuenta" HeaderText="IdCuenta" SortExpression="IdCuenta" />
                    <asp:BoundField DataField="Monto" HeaderText="Monto" SortExpression="Monto" />
                    <asp:CheckBoxField DataField="Tipo" HeaderText="Tipo" SortExpression="Tipo" />
                </Columns>
            </asp:GridView>
            <asp:GridView ID="GridView2" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" DataSourceID="SqlDataSource2">
                <Columns>
                    <asp:CommandField ShowDeleteButton="True" ShowEditButton="True" ShowSelectButton="True" />
                    <asp:BoundField DataField="ID" HeaderText="ID" InsertVisible="False" ReadOnly="True" SortExpression="ID"/>
                    <asp:BoundField DataField="descripcion" HeaderText="descripcion" SortExpression="descripcion" />
                </Columns>
            </asp:GridView>
            <asp:Label ID="Label3" runat="server" Text="Descripcion"></asp:Label>
            <asp:Button ID="Button2" runat="server" Text="Confirmar" />
            
        </div>
    </form>
</body>
</html>
