<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm1.aspx.cs" Inherits="WebApplication4.WebForm1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:lp3ConnectionString2 %>" SelectCommand="SELECT * FROM [RegistroContable]" DeleteCommand="DELETE FROM RegistroConsulta where id = @id" UpdateCommand="UPDATE [RegistroContable] SET [IdCuenta] = @IdCuenta, [Monto] = @Monto, [Tipo] = @Tipo WHERE [ID] = @ID">
               
                <DeleteParameters>
                    <asp:Parameter Name="ID" />
                </DeleteParameters>
                <UpdateParameters>
                    <asp:Parameter Name="IdCuenta" />
                    <asp:Parameter Name="Monto" />
                    <asp:Parameter Name="ID" />
                    <asp:Parameter Name="Tipo" />
                </UpdateParameters>
            </asp:SqlDataSource>
            <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:lp3ConnectionString2 %>" DeleteCommand="DELETE FROM Cuentas WHERE ID = @ID" SelectCommand="SELECT ID as ID, descripcion FROM CUENTAS" UpdateCommand="UPDATE [Cuentas] SET [Descripcion] = @Descripcion WHERE [ID] = @ID">
                <DeleteParameters>
                    <asp:Parameter Name="ID" />
                </DeleteParameters>
                <UpdateParameters>
                    <asp:Parameter Name="Descripcion" />
                    <asp:Parameter Name="ID" />
                </UpdateParameters>
            </asp:SqlDataSource>
            <asp:GridView ID="GridView1" runat="server" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" AllowSorting="True" AutoGenerateColumns="False" DataSourceID="SqlDataSource1" AllowPaging="True" DataKeyNames="ID">
                <Columns>
                    <asp:CommandField ShowSelectButton="True" />
                    <asp:BoundField DataField="ID" HeaderText="ID" InsertVisible="False" ReadOnly="True" SortExpression="ID" />
                    <asp:BoundField DataField="IdCuenta" HeaderText="IdCuenta" SortExpression="IdCuenta" />
                    <asp:BoundField DataField="Monto" HeaderText="Monto" SortExpression="Monto" />
                    <asp:CheckBoxField DataField="Tipo" HeaderText="Tipo" SortExpression="Tipo" />
                </Columns>
            </asp:GridView>
            <asp:GridView ID="GridView2" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" DataSourceID="SqlDataSource2">
                <Columns>
                    <asp:CommandField ShowDeleteButton="True" ShowEditButton="True" ShowSelectButton="True" />
                    <asp:BoundField DataField="ID" HeaderText="ID" InsertVisible="False" ReadOnly="True" SortExpression="ID"/>
                    <asp:BoundField DataField="descripcion" HeaderText="descripcion" SortExpression="descripcion" />
                </Columns>
            </asp:GridView>
        </div>
    </form>
</body>
</html>
